import uuid

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

# Country codes follow ISO 3166-1 (alpha-2 and alpha-3)
# https://www.iso.org/iso-3166-country-codes.html
# Geographic regions are financial market groupings; continents follow UN M49.
# (country_code, country_desc, country_code_iso_alpha3, geographic_region, continent, is_active)
DEFAULT_COUNTRIES = [
    ("NOT SPECIFIED", "Not Specified", None, None, None, True),
    ("AE", "UNITED ARAB EMIRATES", "ARE", "Middle East", "Asia", True),
    ("AR", "ARGENTINA", "ARG", "South America", "Americas", True),
    ("AT", "AUSTRIA", "AUT", "Western Europe", "Europe", True),
    ("AU", "AUSTRALIA", "AUS", "Australia", "Oceania", True),
    ("BE", "BELGIUM", "BEL", "Western Europe", "Europe", True),
    ("BG", "BULGARIA", "BGR", "Eastern Europe", "Europe", True),
    ("BM", "BERMUDA", "BMU", "Caribbean", "Americas", True),
    ("BR", "BRAZIL", "BRA", "South America", "Americas", True),
    ("CA", "CANADA", "CAN", "Canada", "Americas", True),
    ("CH", "SWITZERLAND", "CHE", "Western Europe", "Europe", True),
    ("CL", "CHILE", "CHL", "South America", "Americas", True),
    ("CN", "CHINA", "CHN", "Greater China", "Asia", True),
    ("CZ", "CZECHIA", "CZE", "Eastern Europe", "Europe", True),
    ("DE", "GERMANY", "DEU", "Western Europe", "Europe", True),
    ("DK", "DENMARK", "DNK", "Western Europe", "Europe", True),
    ("EG", "EGYPT", "EGY", "Middle East", "Africa", True),
    ("ES", "SPAIN", "ESP", "Western Europe", "Europe", True),
    ("FI", "FINLAND", "FIN", "Western Europe", "Europe", True),
    ("FR", "FRANCE", "FRA", "Western Europe", "Europe", True),
    ("GB", "UNITED KINGDOM", "GBR", "UK", "Europe", True),
    ("GR", "GREECE", "GRC", "Western Europe", "Europe", True),
    ("HK", "HONG KONG", "HKG", "Greater China", "Asia", True),
    ("HR", "CROATIA", "HRV", "Eastern Europe", "Europe", True),
    ("HU", "HUNGARY", "HUN", "Eastern Europe", "Europe", True),
    ("ID", "INDONESIA", "IDN", "ASEAN", "Asia", True),
    ("IE", "IRELAND", "IRL", "Western Europe", "Europe", True),
    ("IL", "ISRAEL", "ISR", "Middle East", "Asia", True),
    ("IN", "INDIA", "IND", "Other Asia", "Asia", True),
    ("IS", "ICELAND", "ISL", "Western Europe", "Europe", True),
    ("IT", "ITALY", "ITA", "Western Europe", "Europe", True),
    ("JE", "JERSEY", "JEY", None, "Europe", True),
    ("JP", "JAPAN", "JPN", "Japan", "Asia", True),
    ("KR", "KOREA, REPUBLIC OF", "KOR", "Korea", "Asia", True),
    ("LU", "LUXEMBOURG", "LUX", "Western Europe", "Europe", True),
    ("ME", "MONTENEGRO", "MNE", "Eastern Europe", "Europe", True),
    ("MX", "MEXICO", "MEX", "North America", "Americas", True),
    ("MY", "MALAYSIA", "MYS", "ASEAN", "Asia", True),
    ("NL", "NETHERLANDS", "NLD", "Western Europe", "Europe", True),
    ("NO", "NORWAY", "NOR", "Western Europe", "Europe", True),
    ("NZ", "NEW ZEALAND", "NZL", "Oceania", "Oceania", True),
    ("PH", "PHILIPPINES", "PHL", "ASEAN", "Asia", True),
    ("PL", "POLAND", "POL", "Eastern Europe", "Europe", True),
    ("PT", "PORTUGAL", "PRT", "Western Europe", "Europe", True),
    ("RU", "RUSSIAN FEDERATION", "RUS", "Eastern Europe", "Europe", True),
    ("SA", "SAUDI ARABIA", "SAU", "Middle East", "Asia", True),
    ("SE", "SWEDEN", "SWE", "Western Europe", "Europe", True),
    ("SG", "SINGAPORE", "SGP", "ASEAN", "Asia", True),
    ("TH", "THAILAND", "THA", "ASEAN", "Asia", True),
    ("TR", "TURKIYE", "TUR", "Eastern Europe", "Europe", True),
    ("TW", "TAIWAN, PROVINCE OF CHINA", "TWN", "Greater China", "Asia", True),
    ("US", "UNITED STATES", "USA", "United States", "Americas", True),
    ("UY", "URUGUAY", "URY", "South America", "Americas", True),
    ("ZA", "SOUTH AFRICA", "ZAF", "Africa", "Africa", True),
    # Additional countries
    ("AD", "ANDORRA", "AND", None, None, True),
    ("AF", "AFGHANISTAN", "AFG", None, None, True),
    ("AG", "ANTIGUA AND BARBUDA", "ATG", None, None, True),
    ("AI", "ANGUILLA", "AIA", None, None, True),
    ("AL", "ALBANIA", "ALB", None, None, True),
    ("AM", "ARMENIA", "ARM", None, None, True),
    ("AO", "ANGOLA", "AGO", None, None, True),
    ("AQ", "ANTARCTICA", "ATA", None, None, True),
    ("AS", "AMERICAN SAMOA", "ASM", None, None, True),
    ("AW", "ARUBA", "ABW", None, None, True),
    ("AX", "ALAND ISLANDS", "ALA", None, None, True),
    ("AZ", "AZERBAIJAN", "AZE", None, None, True),
    ("BA", "BOSNIA AND HERZEGOVINA", "BIH", None, None, True),
    ("BB", "BARBADOS", "BRB", None, None, True),
    ("BD", "BANGLADESH", "BGD", None, None, True),
    ("BF", "BURKINA FASO", "BFA", None, None, True),
    ("BH", "BAHRAIN", "BHR", None, None, True),
    ("BI", "BURUNDI", "BDI", None, None, True),
    ("BJ", "BENIN", "BEN", None, None, True),
    ("BL", "SAINT BARTHELEMY", "BLM", None, None, True),
    ("BN", "BRUNEI DARUSSALAM", "BRN", None, None, True),
    ("BO", "BOLIVIA, PLURINATIONAL STATE OF", "BOL", None, None, True),
    ("BQ", "BONAIRE, SAINT EUSTATIUS AND SABA", "BES", None, None, True),
    ("BS", "BAHAMAS", "BHS", None, None, True),
    ("BT", "BHUTAN", "BTN", None, None, True),
    ("BV", "BOUVET ISLAND", "BVT", None, None, True),
    ("BW", "BOTSWANA", "BWA", None, None, True),
    ("BY", "BELARUS", "BLR", None, None, True),
    ("BZ", "BELIZE", "BLZ", None, None, True),
    ("CC", "COCOS (KEELING) ISLANDS", "CCK", None, None, True),
    ("CD", "CONGO, THE DEMOCRATIC REPUBLIC OF THE", "COD", None, None, True),
    ("CF", "CENTRAL AFRICAN REPUBLIC", "CAF", None, None, True),
    ("CG", "CONGO", "COG", None, None, True),
    ("CI", "COTE D'IVOIRE", "CIV", None, None, True),
    ("CK", "COOK ISLANDS", "COK", None, None, True),
    ("CM", "CAMEROON", "CMR", None, None, True),
    ("CO", "COLOMBIA", "COL", None, None, True),
    ("CR", "COSTA RICA", "CRI", None, None, True),
    ("CU", "CUBA", "CUB", None, None, True),
    ("CV", "CABO VERDE", "CPV", None, None, True),
    ("CW", "CURACAO", "CUW", None, None, True),
    ("CX", "CHRISTMAS ISLAND", "CXR", None, None, True),
    ("CY", "CYPRUS", "CYP", None, None, True),
    ("DJ", "DJIBOUTI", "DJI", None, None, True),
    ("DM", "DOMINICA", "DMA", None, None, True),
    ("DO", "DOMINICAN REPUBLIC", "DOM", None, None, True),
    ("DZ", "ALGERIA", "DZA", None, None, True),
    ("EC", "ECUADOR", "ECU", None, None, True),
    ("EE", "ESTONIA", "EST", None, None, True),
    ("EH", "WESTERN SAHARA", "ESH", None, None, True),
    ("ER", "ERITREA", "ERI", None, None, True),
    ("ET", "ETHIOPIA", "ETH", None, None, True),
    ("FJ", "FIJI", "FJI", None, None, True),
    ("FK", "FALKLAND ISLANDS (MALVINAS)", "FLK", None, None, True),
    ("FM", "MICRONESIA, FEDERATED STATES OF", "FSM", None, None, True),
    ("FO", "FAROE ISLANDS", "FRO", None, None, True),
    ("GA", "GABON", "GAB", None, None, True),
    ("GD", "GRENADA", "GRD", None, None, True),
    ("GE", "GEORGIA", "GEO", None, None, True),
    ("GF", "FRENCH GUIANA", "GUF", None, None, True),
    ("GG", "GUERNSEY", "GGY", None, None, True),
    ("GH", "GHANA", "GHA", None, None, True),
    ("GI", "GIBRALTAR", "GIB", None, None, True),
    ("GL", "GREENLAND", "GRL", None, None, True),
    ("GM", "GAMBIA", "GMB", None, None, True),
    ("GN", "GUINEA", "GIN", None, None, True),
    ("GP", "GUADELOUPE", "GLP", None, None, True),
    ("GQ", "EQUATORIAL GUINEA", "GNQ", None, None, True),
    ("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "SGS", None, None, True),
    ("GT", "GUATEMALA", "GTM", None, None, True),
    ("GU", "GUAM", "GUM", None, None, True),
    ("GW", "GUINEA-BISSAU", "GNB", None, None, True),
    ("GY", "GUYANA", "GUY", None, None, True),
    ("HM", "HEARD ISLAND AND MCDONALD ISLANDS", "HMD", None, None, True),
    ("HN", "HONDURAS", "HND", None, None, True),
    ("HT", "HAITI", "HTI", None, None, True),
    ("IM", "ISLE OF MAN", "IMN", None, None, True),
    ("IO", "BRITISH INDIAN OCEAN TERRITORY", "IOT", None, None, True),
    ("IQ", "IRAQ", "IRQ", None, None, True),
    ("IR", "IRAN, ISLAMIC REPUBLIC OF", "IRN", None, None, True),
    ("JM", "JAMAICA", "JAM", None, None, True),
    ("JO", "JORDAN", "JOR", None, None, True),
    ("KE", "KENYA", "KEN", None, None, True),
    ("KG", "KYRGYZSTAN", "KGZ", None, None, True),
    ("KH", "CAMBODIA", "KHM", None, None, True),
    ("KI", "KIRIBATI", "KIR", None, None, True),
    ("KM", "COMOROS", "COM", None, None, True),
    ("KN", "SAINT KITTS AND NEVIS", "KNA", None, None, True),
    ("KP", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "PRK", None, None, True),
    ("KW", "KUWAIT", "KWT", None, None, True),
    ("KY", "CAYMAN ISLANDS", "CYM", None, None, True),
    ("KZ", "KAZAKHSTAN", "KAZ", None, None, True),
    ("LA", "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LAO", None, None, True),
    ("LB", "LEBANON", "LBN", None, None, True),
    ("LC", "SAINT LUCIA", "LCA", None, None, True),
    ("LI", "LIECHTENSTEIN", "LIE", None, None, True),
    ("LK", "SRI LANKA", "LKA", None, None, True),
    ("LR", "LIBERIA", "LBR", None, None, True),
    ("LS", "LESOTHO", "LSO", None, None, True),
    ("LT", "LITHUANIA", "LTU", None, None, True),
    ("LV", "LATVIA", "LVA", None, None, True),
    ("LY", "LIBYA", "LBY", None, None, True),
    ("MA", "MOROCCO", "MAR", None, None, True),
    ("MC", "MONACO", "MCO", None, None, True),
    ("MD", "MOLDOVA, REPUBLIC OF", "MDA", None, None, True),
    ("MF", "SAINT MARTIN (FRENCH PART)", "MAF", None, None, True),
    ("MG", "MADAGASCAR", "MDG", None, None, True),
    ("MH", "MARSHALL ISLANDS", "MHL", None, None, True),
    ("MK", "NORTH MACEDONIA", "MKD", None, None, True),
    ("ML", "MALI", "MLI", None, None, True),
    ("MM", "MYANMAR", "MMR", None, None, True),
    ("MN", "MONGOLIA", "MNG", None, None, True),
    ("MO", "MACAO", "MAC", None, None, True),
    ("MP", "NORTHERN MARIANA ISLANDS", "MNP", None, None, True),
    ("MQ", "MARTINIQUE", "MTQ", None, None, True),
    ("MR", "MAURITANIA", "MRT", None, None, True),
    ("MS", "MONTSERRAT", "MSR", None, None, True),
    ("MT", "MALTA", "MLT", None, None, True),
    ("MU", "MAURITIUS", "MUS", None, None, True),
    ("MV", "MALDIVES", "MDV", None, None, True),
    ("MW", "MALAWI", "MWI", None, None, True),
    ("MZ", "MOZAMBIQUE", "MOZ", None, None, True),
    ("NA", "NAMIBIA", "NAM", None, None, True),
    ("NC", "NEW CALEDONIA", "NCL", None, None, True),
    ("NE", "NIGER", "NER", None, None, True),
    ("NF", "NORFOLK ISLAND", "NFK", None, None, True),
    ("NG", "NIGERIA", "NGA", None, None, True),
    ("NI", "NICARAGUA", "NIC", None, None, True),
    ("NP", "NEPAL", "NPL", None, None, True),
    ("NR", "NAURU", "NRU", None, None, True),
    ("NU", "NIUE", "NIU", None, None, True),
    ("OM", "OMAN", "OMN", None, None, True),
    ("PA", "PANAMA", "PAN", None, None, True),
    ("PE", "PERU", "PER", None, None, True),
    ("PF", "FRENCH POLYNESIA", "PYF", None, None, True),
    ("PG", "PAPUA NEW GUINEA", "PNG", None, None, True),
    ("PK", "PAKISTAN", "PAK", None, None, True),
    ("PM", "SAINT PIERRE AND MIQUELON", "SPM", None, None, True),
    ("PN", "PITCAIRN", "PCN", None, None, True),
    ("PR", "PUERTO RICO", "PRI", None, None, True),
    ("PS", "PALESTINIAN TERRITORY, OCCUPIED", "PSE", None, None, True),
    ("PW", "PALAU", "PLW", None, None, True),
    ("PY", "PARAGUAY", "PRY", None, None, True),
    ("QA", "QATAR", "QAT", None, None, True),
    ("RE", "REUNION", "REU", None, None, True),
    ("RO", "ROMANIA", "ROU", None, None, True),
    ("RS", "SERBIA", "SRB", None, None, True),
    ("RW", "RWANDA", "RWA", None, None, True),
    ("SB", "SOLOMON ISLANDS", "SLB", None, None, True),
    ("SC", "SEYCHELLES", "SYC", None, None, True),
    ("SD", "SUDAN", "SDN", None, None, True),
    ("SH", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "SHN", None, None, True),
    ("SI", "SLOVENIA", "SVN", None, None, True),
    ("SJ", "SVALBARD AND JAN MAYEN", "SJM", None, None, True),
    ("SK", "SLOVAKIA", "SVK", None, None, True),
    ("SL", "SIERRA LEONE", "SLE", None, None, True),
    ("SM", "SAN MARINO", "SMR", None, None, True),
    ("SN", "SENEGAL", "SEN", None, None, True),
    ("SO", "SOMALIA", "SOM", None, None, True),
    ("SR", "SURINAME", "SUR", None, None, True),
    ("SS", "SOUTH SUDAN", "SSD", None, None, True),
    ("ST", "SAO TOME AND PRINCIPE", "STP", None, None, True),
    ("SV", "EL SALVADOR", "SLV", None, None, True),
    ("SX", "SINT MAARTEN (DUTCH PART)", "SXM", None, None, True),
    ("SY", "SYRIAN ARAB REPUBLIC", "SYR", None, None, True),
    ("SZ", "ESWATINI", "SWZ", None, None, True),
    ("TC", "TURKS AND CAICOS ISLANDS", "TCA", None, None, True),
    ("TD", "CHAD", "TCD", None, None, True),
    ("TF", "FRENCH SOUTHERN TERRITORIES", "ATF", None, None, True),
    ("TG", "TOGO", "TGO", None, None, True),
    ("TJ", "TAJIKISTAN", "TJK", None, None, True),
    ("TK", "TOKELAU", "TKL", None, None, True),
    ("TL", "TIMOR-LESTE", "TLS", None, None, True),
    ("TM", "TURKMENISTAN", "TKM", None, None, True),
    ("TN", "TUNISIA", "TUN", None, None, True),
    ("TO", "TONGA", "TON", None, None, True),
    ("TT", "TRINIDAD AND TOBAGO", "TTO", None, None, True),
    ("TV", "TUVALU", "TUV", None, None, True),
    ("TZ", "TANZANIA, UNITED REPUBLIC OF", "TZA", None, None, True),
    ("UA", "UKRAINE", "UKR", None, None, True),
    ("UG", "UGANDA", "UGA", None, None, True),
    ("UM", "UNITED STATES MINOR OUTLYING ISLANDS", "UMI", None, None, True),
    ("UZ", "UZBEKISTAN", "UZB", None, None, True),
    ("VA", "HOLY SEE (VATICAN CITY STATE)", "VAT", None, None, True),
    ("VC", "SAINT VINCENT AND THE GRENADINES", "VCT", None, None, True),
    ("VE", "VENEZUELA, BOLIVARIAN REPUBLIC OF", "VEN", None, None, True),
    ("VG", "VIRGIN ISLANDS, BRITISH", "VGB", None, None, True),
    ("VI", "VIRGIN ISLANDS, U.S.", "VIR", None, None, True),
    ("VN", "VIET NAM", "VNM", None, None, True),
    ("VU", "VANUATU", "VUT", None, None, True),
    ("WF", "WALLIS AND FUTUNA", "WLF", None, None, True),
    ("WS", "SAMOA", "WSM", None, None, True),
    ("YE", "YEMEN", "YEM", None, None, True),
    ("YT", "MAYOTTE", "MYT", None, None, True),
    ("ZM", "ZAMBIA", "ZMB", None, None, True),
    ("ZW", "ZIMBABWE", "ZWE", None, None, True),
]


async def insert_default_countries_for_tenant(session: AsyncSession, tenant_id: uuid.UUID) -> int:
    inserted = 0
    for code, desc, iso3, region, continent, active in DEFAULT_COUNTRIES:
        result = await session.execute(
            text("SELECT COUNT(*) FROM countries WHERE country_code = :code AND tenant_id = :tid"),
            {"code": code, "tid": tenant_id},
        )
        if result.scalar() == 0:
            await session.execute(
                text("""
                    INSERT INTO countries (country_code, country_desc, country_code_iso_alpha3, geographic_region, continent, is_active, tenant_id, created_at)
                    VALUES (:code, :desc, :iso3, :region, :continent, :active, :tid, NOW())
                """),
                {"code": code, "desc": desc, "iso3": iso3, "region": region, "continent": continent, "active": active, "tid": tenant_id},
            )
            inserted += 1
    return inserted
