import uuid

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

# Based on ISO 4217 currency codes
# https://www.iso.org/iso-4217-currency-codes.html
DEFAULT_CURRENCIES = [
    ("NOT SPECIFIED", "Not Specified", True),
    ("AED", "United Arab Emirates Dirham", True),
    ("AFN", "Afghanistan Afghani", True),
    ("ALL", "Albania Lek", True),
    ("AMD", "Armenia Dram", True),
    ("ANG", "Netherlands Antilles Guilder", True),
    ("AOA", "Angola Kwanza", True),
    ("ARS", "Argentina Peso", True),
    ("AUD", "Australia Dollar", True),
    ("AWG", "Aruba Guilder", True),
    ("AZN", "Azerbaijani Manat", True),
    ("BAM", "Bosnia and Herzegovina Convertible Marka", True),
    ("BBD", "Barbados Dollar", True),
    ("BDT", "Bangladesh Taka", True),
    ("BGN", "Bulgaria Lev", True),
    ("BHD", "Bahrain Dinar", True),
    ("BIF", "Burundi Franc", True),
    ("BMD", "Bermuda Dollar", True),
    ("BND", "Brunei Darussalam Dollar", True),
    ("BOB", "Bolivia Boliviano", True),
    ("BRL", "Brazil Real", True),
    ("BSD", "Bahamas Dollar", True),
    ("BTN", "Bhutan Ngultrum", True),
    ("BWP", "Botswana Pula", True),
    ("BYN", "Belarusian Ruble", True),
    ("BZD", "Belize Dollar", True),
    ("CAD", "Canada Dollar", True),
    ("CDF", "Congo/Kinshasa Franc", True),
    ("CHF", "Switzerland Franc", True),
    ("CLP", "Chile Peso", True),
    ("CNY", "China Yuan Renminbi", True),
    ("COP", "Colombia Peso", True),
    ("CRC", "Costa Rica Colon", True),
    ("CUP", "Cuba Peso", True),
    ("CVE", "Cabo Verde Escudo", True),
    ("CZK", "Czech Koruna", True),
    ("DJF", "Djibouti Franc", True),
    ("DKK", "Denmark Krone", True),
    ("DOP", "Dominican Republic Peso", True),
    ("DZD", "Algeria Dinar", True),
    ("EGP", "Egypt Pound", True),
    ("ERN", "Eritrea Nakfa", True),
    ("ETB", "Ethiopia Birr", True),
    ("EUR", "Euro", True),
    ("FJD", "Fiji Dollar", True),
    ("FKP", "Falkland Islands (Malvinas) Pound", True),
    ("GBP", "United Kingdom Pound", True),
    ("GEL", "Georgia Lari", True),
    ("GHS", "Ghana Cedi", True),
    ("GIP", "Gibraltar Pound", True),
    ("GMD", "Gambia Dalasi", True),
    ("GNF", "Guinea Franc", True),
    ("GTQ", "Guatemala Quetzal", True),
    ("GYD", "Guyana Dollar", True),
    ("HKD", "Hong Kong Dollar", True),
    ("HNL", "Honduras Lempira", True),
    ("HTG", "Haiti Gourde", True),
    ("HUF", "Hungary Forint", True),
    ("IDR", "Indonesia Rupiah", True),
    ("ILS", "Israeli New Sheqel", True),
    ("INR", "India Rupee", True),
    ("IQD", "Iraq Dinar", True),
    ("IRR", "Iran Rial", True),
    ("ISK", "Iceland Krona", True),
    ("JMD", "Jamaica Dollar", True),
    ("JOD", "Jordan Dinar", True),
    ("JPY", "Japan Yen", True),
    ("KES", "Kenya Shilling", True),
    ("KGS", "Kyrgyzstan Som", True),
    ("KHR", "Cambodia Riel", True),
    ("KMF", "Comoros Franc", True),
    ("KPW", "Korea (North) Won", True),
    ("KRW", "Korea (South) Won", True),
    ("KWD", "Kuwait Dinar", True),
    ("KYD", "Cayman Islands Dollar", True),
    ("KZT", "Kazakhstan Tenge", True),
    ("LAK", "Laos Kip", True),
    ("LBP", "Lebanon Pound", True),
    ("LKR", "Sri Lanka Rupee", True),
    ("LRD", "Liberia Dollar", True),
    ("LSL", "Lesotho Loti", True),
    ("LYD", "Libya Dinar", True),
    ("MAD", "Morocco Dirham", True),
    ("MDL", "Moldova Leu", True),
    ("MGA", "Madagascar Ariary", True),
    ("MKD", "North Macedonia Denar", True),
    ("MMK", "Myanmar (Burma) Kyat", True),
    ("MNT", "Mongolia Tughrik", True),
    ("MOP", "Macau Pataca", True),
    ("MRU", "Mauritanian Ouguiya", True),
    ("MUR", "Mauritius Rupee", True),
    ("MVR", "Maldives (Maldive Islands) Rufiyaa", True),
    ("MWK", "Malawi Kwacha", True),
    ("MXN", "Mexico Peso", True),
    ("MYR", "Malaysia Ringgit", True),
    ("MZN", "Mozambique Metical", True),
    ("NAD", "Namibia Dollar", True),
    ("NGN", "Nigeria Naira", True),
    ("NIO", "Nicaragua Cordoba", True),
    ("NOK", "Norway Krone", True),
    ("NPR", "Nepal Rupee", True),
    ("NZD", "New Zealand Dollar", True),
    ("OMR", "Oman Rial", True),
    ("PAB", "Panama Balboa", True),
    ("PEN", "Peruvian Sol", True),
    ("PGK", "Papua New Guinea Kina", True),
    ("PHP", "Philippines Peso", True),
    ("PKR", "Pakistan Rupee", True),
    ("PLN", "Poland Zloty", True),
    ("PYG", "Paraguay Guarani", True),
    ("QAR", "Qatar Riyal", True),
    ("RON", "Romanian Leu", True),
    ("RSD", "Serbia Dinar", True),
    ("RUB", "Russia Ruble", True),
    ("RWF", "Rwanda Franc", True),
    ("SAR", "Saudi Arabia Riyal", True),
    ("SBD", "Solomon Islands Dollar", True),
    ("SCR", "Seychelles Rupee", True),
    ("SDG", "Sudan Pound", True),
    ("SEK", "Sweden Krona", True),
    ("SGD", "Singapore Dollar", True),
    ("SHP", "Saint Helena Pound", True),
    ("SLE", "Sierra Leonean Leone", True),
    ("SOS", "Somalia Shilling", True),
    ("SRD", "Suriname Dollar", True),
    ("SSP", "South Sudanese Pound", True),
    ("STN", "Sao Tome and Principe Dobra", True),
    ("SVC", "El Salvador Colon", True),
    ("SYP", "Syria Pound", True),
    ("SZL", "Eswatini Lilangeni", True),
    ("THB", "Thailand Baht", True),
    ("TJS", "Tajikistan Somoni", True),
    ("TMT", "Turkmenistan Manat", True),
    ("TND", "Tunisia Dinar", True),
    ("TOP", "Tonga Pa'anga", True),
    ("TRY", "Turkish Lira", True),
    ("TTD", "Trinidad and Tobago Dollar", True),
    ("TWD", "Taiwan New Dollar", True),
    ("TZS", "Tanzania Shilling", True),
    ("UAH", "Ukrainian Hryvnia", True),
    ("UGX", "Uganda Shilling", True),
    ("USD", "United States Dollar", True),
    ("UYU", "Uruguay Peso", True),
    ("UZS", "Uzbekistan Som", True),
    ("VES", "Venezuelan Bolivar Soberano", True),
    ("VND", "Viet Nam Dong", True),
    ("VUV", "Vanuatu Vatu", True),
    ("WST", "Samoa Tala", True),
    ("XAF", "Communaute Financiere Africaine (BEAC) CFA Franc BEAC", True),
    ("XAG", "Silver Ounce", True),
    ("XAU", "Gold Ounce", True),
    ("XCD", "East Caribbean Dollar", True),
    ("XDR", "International Monetary Fund (IMF) Special Drawing Rights", True),
    ("XOF", "Communaute Financiere Africaine (BCEAO) Franc", True),
    ("XPD", "Palladium Ounce", True),
    ("XPF", "Comptoirs Francais du Pacifique (CFP) Franc", True),
    ("XPT", "Platinum Ounce", True),
    ("YER", "Yemen Rial", True),
    ("ZAR", "South Africa Rand", True),
    ("ZMW", "Zambian Kwacha", True),
    ("ZWL", "Zimbabwe Dollar", True),
]


async def insert_default_currencies_for_tenant(session: AsyncSession, tenant_id: uuid.UUID) -> int:
    inserted = 0
    for ccy, desc, active in DEFAULT_CURRENCIES:
        result = await session.execute(
            text("SELECT COUNT(*) FROM currencies WHERE ccy = :ccy AND tenant_id = :tid"),
            {"ccy": ccy, "tid": tenant_id},
        )
        if result.scalar() == 0:
            await session.execute(
                text("""
                    INSERT INTO currencies (ccy, ccy_des, is_active, tenant_id, created_at)
                    VALUES (:ccy, :desc, :active, :tid, NOW())
                """),
                {"ccy": ccy, "desc": desc, "active": active, "tid": tenant_id},
            )
            inserted += 1
    return inserted
