"""create staging_holdings table

Revision ID: 04677156f592
Revises: 6b843a246174
Create Date: 2026-02-17 18:12:05.229553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04677156f592'
down_revision: Union[str, None] = '6b843a246174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('security_description', sa.String(length=200), nullable=True),
    sa.Column('issuing_country', sa.String(length=100), nullable=True),
    sa.Column('local_currency', sa.String(length=10), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_local', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('outstanding_shares', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('underlier', sa.String(length=50), nullable=True),
    sa.Column('sedol', sa.String(length=7), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('runid', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_holdings')
    # ### end Alembic commands ###
