"""create fx_rates table

Revision ID: 6b843a246174
Revises: 6e742247f0b0
Create Date: 2026-02-17 18:09:06.976314
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b843a246174'
down_revision: Union[str, None] = '6e742247f0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('ref_currency_id', sa.BigInteger(), nullable=False),
    sa.Column('currency_id', sa.BigInteger(), nullable=False),
    sa.Column('direct', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('indirect', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('last_modified_by', sa.String(length=30), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['ref_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fx_rates_rate_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
