"""create holdings table

Revision ID: 6cfe91d9058d
Revises: 6b843a246174
Create Date: 2026-02-17 18:16:39.110055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfe91d9058d'
down_revision: Union[str, None] = '6b843a246174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('holding_date', sa.Date(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('fund_id', sa.BigInteger(), nullable=False),
    sa.Column('custodian_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('quantity_start', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_end', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cost_local', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_base', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_local', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('outstanding_shares', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("side IN ('Long', 'Short')", name='holding_side_check'),
    sa.ForeignKeyConstraint(['custodian_id'], ['custodians.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    # ### end Alembic commands ###
