"""create securities table

Revision ID: bd0bda8137bc
Revises: b7061c23f311
Create Date: 2026-02-16 22:08:10.148719
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0bda8137bc'
down_revision: Union[str, None] = 'b7061c23f311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('security_des', sa.String(length=200), nullable=True),
    sa.Column('id_1', sa.String(length=50), nullable=True),
    sa.Column('id_2', sa.String(length=50), nullable=True),
    sa.Column('id_3', sa.String(length=50), nullable=True),
    sa.Column('cntry_of_risk_id', sa.BigInteger(), nullable=True),
    sa.Column('cntry_of_domicile_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('coupon', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('first_coupon_date', sa.Date(), nullable=True),
    sa.Column('penultimate_coupon_date', sa.Date(), nullable=True),
    sa.Column('last_update_date', sa.Date(), nullable=True),
    sa.Column('ccy_id', sa.BigInteger(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('security_subtype_id', sa.BigInteger(), nullable=True),
    sa.Column('asset_type_id', sa.BigInteger(), nullable=True),
    sa.Column('market_category_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.ForeignKeyConstraint(['ccy_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['cntry_of_domicile_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['cntry_of_risk_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['market_category_id'], ['market_categories.id'], ),
    sa.ForeignKeyConstraint(['security_subtype_id'], ['security_subtypes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    # ### end Alembic commands ###
